dist: trusty
sudo: false

os:
  - linux

language:
  - cpp

addons:
  apt:
    packages:
      - libglu1-mesa-dev
      - uuid-dev
      - libboost-filesystem-dev
      - libboost-regex-dev
      - libboost-system-dev
      - ant
      - oracle-java8-set-default

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  # install newer Meson than is packaged in repos
  - pip3 install --user meson
  - meson --version
  # download newer Ninja than is packaged in repos
  - curl -L -s https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip -o ninja-linux.zip
  - unzip ninja-linux.zip
  - mv ninja ~/.local/bin
  - ninja --version

install:
  # clone, build, and run LmcpGen
  - git clone -b $TRAVIS_BRANCH git@github.com:afrl-rq/LmcpGen.git ../LmcpGen
  - (cd ../LmcpGen; ant jar)
  - sh RunLmcpGen.sh
  # process the wraps and their patches
  - ./prepare

before_script:
  - meson build

script:
  # build with -j2; Travis has 2 "cores"
  - ninja -C build test -j2
  
